server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://114.55.253.132:3306/myblog?userUnicode=true&characterEncoding=utf-8&userSSL=false
    username: hanshan
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    mode: HTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
    cache: false
    prefix: classpath:templates/
mybatis:
  mapper-locations: classpath:mapper/*.xml
