server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://192.168.195.133:3306/myblog?userUnicode=true&characterEncoding=utf-8&userSSL=false
    username: hanshan
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver